version: '1.00'

services:
  react:
    build:
      context: ./frontend 
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  
      - /app/node_modules 
    working_dir: /app 
    command: ["npm", "start"] 
    environment:
      - WATCHPACK_POLLING=true

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
